name: Shellcheck and write-good

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.1.0
  
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    steps:
    - uses: actions/checkout@v2

    - name: Lint Markdown
      uses: tomwhross/write-good-action@v1.5
    - name: write-good output
      run: echo "${{ steps.write-good.outputs.result }}"
    
